--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PocketCloudSystem/discord-webhook-lib
build-by-default: true
branches:
- pmmp
projects:
  discord-webhook-lib:
    path: ""
    model: virion
    type: library
...
